### ISSUE TITLE
Example fails with "SyntaxError: EOL while scanning string literal"

### ISSUE THREAD

**Issue by jonasbb** [vitapluvia/pwnUp#1]
While trying to reproduce the example I get this error.
Python: 2.7.13
Fedora: 25

```
jbushart@latitude ~ [1]> pwnup bandit.labs.overthewire.org 22                                                                                                             Thu 16 Feb 15:00:08 CET 2017
[*] Running PwnUp 1.0.6
 [?] Choose a type.
    1> 1) ssh
       2) remote
       3) local
[*] You Chose: ssh
user > bandit0
password > bandit0
cmd > cat readme
Traceback (most recent call last):
  File "/usr/bin/pwnup", line 11, in <module>
    sys.exit(start())
  File "/usr/lib/python2.7/site-packages/pwnup/pwnup.py", line 149, in start
    PwnUp().run()
  File "/usr/lib/python2.7/site-packages/pwnup/pwnup.py", line 143, in run
    interaction = self.interact(connection)
  File "/usr/lib/python2.7/site-packages/pwnup/pwnup.py", line 116, in interact
    exec(connection)
  File "<string>", line 1
    sh = ssh(host='bandit.labs.overthewire.org', user='bandit0
                                                             ^
SyntaxError: EOL while scanning string literal
```

**Comment by vitapluvia** [comment]
Hi @jonasbb! Thanks for trying out the tool!

I'll take a look at this today, so far unable to reproduce, but the `exec` looks like a bad idea regardless.  That's probably causing the issue as well.

May also look into using tox to test this.

**Comment by jonasbb** [comment]
@vitapluvia I tracked it down to this: https://github.com/Gallopsled/pwntools/issues/906

It seems that in some cases the newline is not stripped. `raw_input` works correctly if I run in interactively in ipython.

**Comment by vitapluvia** [comment]
Thanks!! Was just able to reproduce on my machine as well

**Comment by vitapluvia** [comment]
This was tested in an older version of python, `2.7.11` which  may be the actual issue, since `raw_input` comes from python.  To solve this for `pwnup`, I may re-release with a bunch of strip newlines on the raw_input's.  This is a hack, but the whole tool is a hack right now 🔨

**Comment by vitapluvia** [comment]
Pushed out a new version of pwnup, version 1.0.7, this one should work now!  There's also a new debug feature copying the `pwntools` one, when exporting `PWN_DEBUG`.
